version: "3.0"
services:
  node:
    container_name: node
    image: node:16-alpine
    ports:
      - "4000:8080"
    volumes:
      - ./:/usr/local/bin/app
    command: ["node", "/usr/local/bin/app/server.js"]
